### ISSUE TITLE
TypeError: Cannot read property toLocaleUpperCase of undefined at create webdriver

### ISSUE THREAD

**Issue by valdrinnz** [webrtc/KITE#106]
We are trying to run kite tests from azure devops, and we are facing this error. 

TypeError: Cannot read property &#x27;toLocaleUpperCase&#x27; of undefined 
at createWebDriver (&#x2F;KITEUx2F;KITE-TEST-Test&#x2F;js&#x2F;node_modules&#x2F;kite-common&#x2F;wdmgmt&#x2F;WebDriverFactory.js:38:29) 
at Object.getDriver (84x2F;KITE84x2F;KITE-TEST-Test&#x2F;js&#x2F;node_modules84x2F;kite-common&#x2F;wdmgmt&#x2F;WebDriverFactory.js:94:25) 
at TESTtest.testScript (&#x2F;KITE84x2F;KITE-TEST-Test&#x2F;js&#x2F;TESTtest.js:22:44) at TESTtest.run (&#x2F;KITE&#x2F;KITE-TEST-Test&#x2F;js&#x2F;node_modules&#x2F;kite-common&#x2F;util&#x2F;KiteBaseTest.js:106:18) 
at KiteBaseTest (&#x2F;KITE84x2F;KITE-TEST-Test&#x2F;js&#x2F;TESTtest.js:160:14) 
at &lt;anonymous&gt; 
at process._tickCallback (internal&#x2F;process&#x2F;next_tick.js:188:7) 
at Function.Module.runMain (module.js:695:11) 
at startup (bootstrap_node.js:188:16) 
at bootstrap_node.js:609:3 
TypeError: Cannot read property &#x27;quit&#x27; of undefined 
at TESTtest.testScript (84x2F;KITES4x2F;KITE-TEST-Test&#x2F;js&#x2F;TESTtest.js:150:25) at &lt;anonymous&gt; 
at process._tickCallback (internal&#x2F;process&#x2F;next_tick.js:188:7) 
at Function.Module.runMain (module.js:695:11) at startup (bootstrap_node.js:188:16) 
at bootstrap_node.js:609:3 wrote all data to file 

When we run this test from swarm is working good.

**Comment by namvuCosmo** [comment]
Hi,

Sorry, but we currently don't have the bandwidth to maintain the js code at the moment. We will investigate this when we can.

**Comment by namvuCosmo** [comment]
Hello,

We just update the repository to fix Js test error. The test should run normally now.

Can you give it a try?

**Comment by valdrinnz** [comment]
Yeah thank you, it's fixed now. Look like we had problems with KITE version.
