### ISSUE TITLE
Hub Configuration

### ISSUE THREAD

**Issue by CMor1184** [webrtc/KITE#130]
Hi,

I have problems that my nodes can't reach the hub. To check why I have started the hub manually with the script "/localGrid/hub/startHub.sh" and I get following exception:

Exception in thread "main" org.openqa.grid.common.exception.GridConfigurationException: Error creating class with io.cosmosoftware.kite.grid.KiteCapabilityMatcher : io.cosmosoftware.kite.grid.KiteCapabilityMatcher
	at org.openqa.grid.internal.cli.StringToClassConverter.convert(StringToClassConverter.java:31)
	at com.beust.jcommander.JCommander.convertValue(JCommander.java:1472)
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:238)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:895)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:870)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:721)
	at com.beust.jcommander.JCommander.parse(JCommander.java:340)
	at com.beust.jcommander.JCommander.parse(JCommander.java:319)
	at org.openqa.grid.selenium.GridLauncherV3.parse(GridLauncherV3.java:218)
	at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$5(GridLauncherV3.java:255)
	at org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86)
	at java.util.Optional.map(Optional.java:215)
	at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70)
Caused by: java.lang.ClassNotFoundException: io.cosmosoftware.kite.grid.KiteCapabilityMatcher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.openqa.grid.internal.cli.StringToClassConverter.convert(StringToClassConverter.java:29)

gridConfig:

Set to TRUE to install Chrome and Firefox, or FALSE to skip this step if the correct versions are already installed.
export INSTALL_BROWSERS=TRUE

Set to TRUE/FALSE to enable/disable the CAPABILITY MATCHER
export USE_CAPABILITY_MATCHER=TRUE

Set to TRUE if this is a full desktop environment, FALSE if it's without any display
export DESKTOP_ENVIRONMENT=TRUE

Set to TRUE to use localhost or FALSE to use the host's IP address
export LOCALHOST=FALSE

ChromeDriver and GeckoDriver versions
export GECKO_VERSION=v0.26.0
export CHROMEDRIVER_VERSION=83.0.4103.39

Selenium version
export SELENIUM_VERSION_SHORT=3.141
export SELENIUM_VERSION=3.141.59

Browser versions
export FIREFOX_VERSION=77
export CHROME_VERSION=83

Capability Matcher
export KITE_EXTRAS_VERSION=0.1.65
export GRID_UTILS_VERSION=0.0.1

What is the problem?

Thanks,

Chris

**Comment by namvuCosmo** [comment]
It's an old feature that we no longer support.

I  tried to clean it up once but clearly I missed something there.

Can you please post the script `/localGrid/hub/startHub.sh` here, I don't have it on hand. There should be a line somewhere in there that you can comment out to bypass this issue.

**Comment by CMor1184** [comment]
I think the problem is that i have set a custom capability matcher (if i set this to FALSE it works fine):

export USE_CAPABILITY_MATCHER=TRUE

The content of the "startHub.sh":

echo -n -e "\033]0;HUB\007"
java -cp *:.:../* org.openqa.grid.selenium.GridLauncherV3 -role hub --debug -host 192.168.1.19 -capabilityMatcher io.cosmosoftware.kite.grid.KiteCapabilityMatcher

**Comment by namvuCosmo** [comment]
Yes, that the thing! Please set it to false.

**Comment by CMor1184** [comment]
Thanks!
