### ISSUE TITLE
JS tests broken

### ISSUE THREAD

**Issue by gitautas** [webrtc/KITE#160]
Javascript tests and _kite_init_ are broken, after running _kite_init_ and running _c_ the test doesn't compile with the following error:

`[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.webrtc.kite:broadcaster-test:0.0.1: Failure to find org.webrtc.kite:kite-base:pom:2.0.7 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 8, column 11
[WARNING] 'version' contains an expression but should be a constant. @ org.webrtc.kite:kite-framework:${kite.framework.version}, /home/gintautas/Projects/KITE/KITE-Framework/pom.xml, line 14, column 12
[WARNING] 'version' contains an expression but should be a constant. @ org.webrtc.kite:kite-engine:${kite.version}, /home/gintautas/Projects/KITE/KITE-Engine/pom.xml, line 14, column 12
[WARNING] 'version' contains an expression but should be a constant. @ org.webrtc.kite:apprtc-test:${kite.apprtc.version}, /home/gintautas/Projects/KITE/KITE-AppRTC-Test/pom.xml, line 16, column 12
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.webrtc.kite:broadcaster-test:0.0.1 (/home/gintautas/Projects/KITE/KITE-Broadcaster-Test/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.webrtc.kite:broadcaster-test:0.0.1: Failure to find org.webrtc.kite:kite-base:pom:2.0.7 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 8, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
`

And when trying to run any of the javascript tests I get this error:
`off
java -Dkite.firefox.profile=/home/gintautas/Projects/KITE/third_party/firefox-h264-profiles/ -cp /home/gintautas/Projects/KITE/KITE-Engine/target/kite-jar-with-dependencies.jar:target/* org.webrtc.kite.Engine ./configs/js.iceconnection.apprtc.config.json
2020-09-29 16:03:43,216 INFO  - Reading '/home/gintautas/Projects/KITE/KITE-AppRTC-Test/./configs/js.iceconnection.apprtc.config.json' ...
 2020-09-29 16:03:43,230 ERROR - javax.json.stream.JsonParsingException: Invalid token=CURLYCLOSE at (line no=34, column no=5, offset=874). Expected tokens are: [STRING]
	at org.glassfish.json.JsonParserImpl.parsingException(JsonParserImpl.java:437)
	at org.glassfish.json.JsonParserImpl.access$1000(JsonParserImpl.java:79)
	at org.glassfish.json.JsonParserImpl$ObjectContext.getNextEvent(JsonParserImpl.java:489)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:363)
	at org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:333)
	at org.glassfish.json.JsonParserImpl.getValue(JsonParserImpl.java:182)
	at org.glassfish.json.JsonParserImpl.getArray(JsonParserImpl.java:326)
	at org.glassfish.json.JsonParserImpl.getValue(JsonParserImpl.java:180)
	at org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:339)
	at org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:173)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:112)
	at io.cosmosoftware.kite.util.TestUtils.readJsonFile(TestUtils.java:842)
	at org.webrtc.kite.config.Configurator.buildConfig(Configurator.java:80)
	at org.webrtc.kite.Engine.buildConfig(Engine.java:75)
	at org.webrtc.kite.Engine.main(Engine.java:153)

 2020-09-29 16:03:43,230 FATAL - FATAL Error: KITE has failed to start execution
 java.lang.NullPointerException
	at org.webrtc.kite.config.Configurator.buildConfig(Configurator.java:82)
	at org.webrtc.kite.Engine.buildConfig(Engine.java:75)
	at org.webrtc.kite.Engine.main(Engine.java:153)
Exception in thread "main" java.lang.NullPointerException
	at org.webrtc.kite.Engine.main(Engine.java:155)
`

Any help fixing this would be appreciated.

**Comment by A-nguyenv** [comment]
Hello,
the JS library is not as supported as the Java since we work mostly in Java. Currently, we do not have the bandwith to look into this but will prioritize your problem as soon as possible.
