### ISSUE TITLE
Webdriver Exception when running Example-Test

### ISSUE THREAD

**Issue by TimoVFX** [webrtc/KITE#186]
Hi, 
i installed KITE following the guide. I have an external Selenium Grid running, changed the url in the `search.local.config.json` 

like so: 
```
  "grids": [
    {
      "type": "local",
      "url": "http://someURL:4444/wd/hub"
    }
  ],

```

When running `kite_r search.local.config.json` within the `KITE-Example-Test` there are occuring two different Errors: 

- `ERROR - unknown(no Web Driver): Exception while populating webdriver: 0
org.webrtc.kite.exception.KiteGridException: WebDriverException creating webdriver for ...`
and 
- `org.openqa.selenium.WebDriverException: Error forwarding the new session cannot find : Capabilities ...`

Full Logs following down below.

I did some research on this errors and its most likely something related to the version of the webdrivers. 
My Versions:
- `chromedriver -v`: 90.0.4430.24
- `google-chrome -v`: 90.0.4430.93
- `grid-chrome`: 90.0.4430.86

I tried it on Windows within WSL, as well as on my Macbook. And i got the same result for both devices.
I also tried to install and use the local grid, resulting in the same errors.
Probably im missing just something minor but i can´t figure it out atm. 

Console output:
```
➜ kite_r search.local.config.json
off
/d/projects/KITE/scripts/linux/path/kite_r: 15: /d/projects/KITE/scripts/linux/path/kite_r: [[: Permission denied
java -Dkite.firefox.profile=/d/projects/KITE/third_party/firefox-h264-profiles/ -cp /d/projects/KITE/KITE-Engine/target/kite-jar-with-dependencies.jar:target/* org.webrtc.kite.Engine configs/search.local.config.json
2021-05-31 15:59:49,113 INFO  - Reading '/d/projects/KITE/KITE-Example-Test/configs/search.local.config.json' ...
 2021-05-31 15:59:49,188 INFO  - new RoomManager(1 max per room) for null
 2021-05-31 15:59:49,188 INFO  - Please make sure that you have enough room for all users.
 2021-05-31 15:59:49,189 INFO  - getRoomUrl(random) function, with random value = true/false, will give you the base url with or without a randomized ID.
 2021-05-31 15:59:49,189 INFO  - Finished reading the configuration file
 2021-05-31 15:59:49,190 INFO  - Creating report folder if not exist at :/d/projects/KITE/KITE-Example-Test/kite-allure-reports/
 2021-05-31 15:59:49,199 INFO  - Running {"type":"interop","name":"KiteExampleSearchTest %ts","testImpl":"org.webrtc.kite.example.KiteExampleSearchTest","description":"This example test opens google and searches for Cosmo Software Consulting and verify the first result","tupleSize":1,"noOfThreads":1,"maxRetryCount":0,"delayForClosing":0,"permute":true} ...
 2021-05-31 15:59:49,208 INFO  - Executing {"type":"interop","name":"KiteExampleSearchTest %ts","testImpl":"org.webrtc.kite.example.KiteExampleSearchTest","description":"This example test opens google and searches for Cosmo Software Consulting and verify the first result","tupleSize":1,"noOfThreads":1,"maxRetryCount":0,"delayForClosing":0,"permute":true} for 1 browser tuples with size :1
 2021-05-31 15:59:49,223 INFO  - current phase in test manager has been set to DEFAULT
 2021-05-31 15:59:49,230 INFO  - 
           |--------------------------------------------------
           | Number of registered tests: 0
           | Elapsed time: 0m0s (avg:0m0s)
           | Running test case with ID: 0/1
           | ETA (for KiteExampleSearchTest %ts): Estimating..
           |--------------------------------------------------
 2021-05-31 15:59:49,231 INFO  - execute(DEFAULT) for the test case: LIN_ch_90 (2021-05-31-155949)
 2021-05-31 15:59:49,233 INFO  - Not load test, init report for test
 2021-05-31 15:59:49,244 INFO  - Finished filling out initial report for phase 
 2021-05-31 15:59:49,244 INFO  - payload handling
 2021-05-31 15:59:49,245 INFO  - the payload is {"test1":"ONE","test2":"TWO"}
 2021-05-31 15:59:49,248 INFO  - Creating runners
 2021-05-31 15:59:49,251 INFO  - Start creating the TestRunner id 0 in 0ms
 2021-05-31 15:59:49,273 INFO  - unknown(no Web Driver): Creating web driver for {"app":false,"kind":"browser","logger":{"name":"org.webrtc.kite.config.client.Client","debugEnabled":true,"appender":{}},"count":5,"clientIndex":0,"fullReset":false,"jsonConfig":{"headless":{},"browserName":{},"version":{},"platform":{}},"capability":{"headless":false,"windowSize":"1920,1200","technologyPreview":false,"useFakeMedia":true,"flags":[],"extraCapabilities":{},"maxInstances":5,"gateway":"none"},"paas":{"specList":[],"networkProfile":{"corrupt":0,"delay":0,"cleanUpCommand":"","bandwidth":0,"packetloss":0,"name":"NONE","id":"","duplicate":0,"command":""},"availableSlots":4,"type":"local","region":"NC","url":"http://someURL:4444/wd/hub"},"name":"0","networkProfile":{"corrupt":0,"delay":0,"cleanUpCommand":"","bandwidth":0,"packetloss":0,"name":"","id":"","duplicate":0,"command":""},"exclude":false,"browserSpecs":{"extension":"","profile":"","driverString":"-Dwebdriver.chrome.driver=./chromedriver","browserName":"chrome","version":"90","deviceName":"unknown","platform":"LINUX"},"region":"NC"}
 2021-05-31 15:59:50,272 ERROR - org.openqa.selenium.WebDriverException: Error forwarding the new session cannot find : Capabilities {browserName: chrome, goog:chromeOptions: {args: [use-fake-ui-for-media-stream, use-fake-device-for-media-s..., enable-automation, no-sandbox, disable-infobars, disable-dev-shm-usage, disable-browser-side-naviga..., disable-gpu, auto-select-desktop-capture..., window-size=1920,1200], extensions: [], prefs: {profile.default_content_setting_values.media_stream_camera: 1, profile.default_content_setting_values.media_stream_mic: 1}}, loggingPrefs: org.openqa.selenium.logging..., pageLoadStrategy: eager, platformName: linux, version: 90}
Command duration or timeout: 362 milliseconds
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
        at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
        at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
        at org.webrtc.kite.WebDriverFactory.createWebDriver(WebDriverFactory.java:229)
        at org.webrtc.kite.config.client.Client.createWebDriver(Client.java:520)
        at org.webrtc.kite.tests.InitClientWebDriverStep.step(InitClientWebDriverStep.java:33)
        at io.cosmosoftware.kite.steps.TestStep.execute(TestStep.java:81)
        at io.cosmosoftware.kite.steps.TestStep.processTestStep(TestStep.java:329)
        at org.webrtc.kite.tests.TestRunner.<init>(TestRunner.java:73)
        at org.webrtc.kite.tests.TestRunnerCreator.call(TestRunnerCreator.java:33)
        at org.webrtc.kite.tests.TestRunnerCreator.call(TestRunnerCreator.java:12)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.WebDriverException: Error forwarding the new session cannot find : Capabilities {browserName: chrome, goog:chromeOptions: {args: [use-fake-ui-for-media-stream, use-fake-device-for-media-s..., enable-automation, no-sandbox, disable-infobars, disable-dev-shm-usage, disable-browser-side-naviga..., disable-gpu, auto-select-desktop-capture..., window-size=1920,1200], extensions: [], prefs: {profile.default_content_setting_values.media_stream_camera: 1, profile.default_content_setting_values.media_stream_mic: 1}}, loggingPrefs: org.openqa.selenium.logging..., pageLoadStrategy: eager, platformName: linux, version: 90}
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'LODUR', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-19041-Microsoft', java.version: '11.0.11'
Driver info: driver.version: unknown
        at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:118)
        at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
        at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)

 2021-05-31 15:59:50,276 ERROR - unknown(no Web Driver): Exception while populating webdriver: 0
org.webrtc.kite.exception.KiteGridException: WebDriverException creating webdriver for 
{"app":false,"kind":"browser","logger":{"name":"org.webrtc.kite.config.client.Client","debugEnabled":true,"appender":{}},"count":5,"clientIndex":0,"fullReset":false,"jsonConfig":{"headless":{},"browserName":{},"version":{},"platform":{}},"capability":{"headless":false,"windowSize":"1920,1200","technologyPreview":false,"useFakeMedia":true,"flags":[],"extraCapabilities":{},"maxInstances":5,"gateway":"none"},"paas":{"specList":[],"networkProfile":{"corrupt":0,"delay":0,"cleanUpCommand":"","bandwidth":0,"packetloss":0,"name":"NONE","id":"","duplicate":0,"command":""},"availableSlots":4,"type":"local","region":"NC","url":"http://someURL:4444/wd/hub"},"name":"0","networkProfile":{"corrupt":0,"delay":0,"cleanUpCommand":"","bandwidth":0,"packetloss":0,"name":"","id":"","duplicate":0,"command":""},"exclude":false,"browserSpecs":{"extension":"","profile":"","driverString":"-Dwebdriver.chrome.driver=./chromedriver","browserName":"chrome","version":"90","deviceName":"unknown","platform":"LINUX"},"region":"NC"}:
Error forwarding the new session cannot find : Capabilities {browserName: chrome, goog:chromeOptions: {args: [use-fake-ui-for-media-stream, use-fake-device-for-media-s..., enable-automation, no-sandbox, disable-infobars, disable-dev-shm-usage, disable-browser-side-naviga..., disable-gpu, auto-select-desktop-capture..., window-size=1920,1200], extensions: [], prefs: {profile.default_content_setting_values.media_stream_camera: 1, profile.default_content_setting_values.media_stream_mic: 1}}, loggingPrefs: org.openqa.selenium.logging..., pageLoadStrategy: eager, platformName: linux, version: 90}
Command duration or timeout: 362 milliseconds
        at org.webrtc.kite.config.client.Client.createWebDriver(Client.java:532)
        at org.webrtc.kite.tests.InitClientWebDriverStep.step(InitClientWebDriverStep.java:33)
        at io.cosmosoftware.kite.steps.TestStep.execute(TestStep.java:81)
        at io.cosmosoftware.kite.steps.TestStep.processTestStep(TestStep.java:329)
        at org.webrtc.kite.tests.TestRunner.<init>(TestRunner.java:73)
        at org.webrtc.kite.tests.TestRunnerCreator.call(TestRunnerCreator.java:33)
        at org.webrtc.kite.tests.TestRunnerCreator.call(TestRunnerCreator.java:12)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

 2021-05-31 15:59:50,280 INFO  - unknown(no Web Driver):  [PASSED] Initiate webDriver for client
 2021-05-31 15:59:50,284 INFO  - Starting the execution of the test runners in parallel 
 2021-05-31 15:59:50,286 INFO  - Start processing the TestRunner(DEFAULT) id 0 in 0ms
 2021-05-31 15:59:50,287 WARN  - unknown(no Web Driver) - 0: [SKIPPING] Open https://google.com and look for CoSMo Software Consulting
 2021-05-31 15:59:50,288 WARN  - unknown(no Web Driver) - 0: [SKIPPING] Open first result on Google result page and verify the page title
 2021-05-31 15:59:50,288 INFO  - execute(DEFAULT) completed.
 2021-05-31 15:59:50,289 INFO  - Terminating, quiting webdriver
 2021-05-31 15:59:50,292 INFO  - Closing down webDrivers
 2021-05-31 15:59:50,299 INFO  - Test PASSED
 2021-05-31 15:59:50,300 INFO  - Matrix runner at last phase, ending. 
 2021-05-31 15:59:50,319 WARN  - Done! All test cases have passed!
 2021-05-31 15:59:50,320 INFO  - shutdownExecutors() done. ```

**Comment by A-nguyenv** [comment]
Hello,
This error occurs when the specified browser version is not available on the grid.
Could you please double check the version you specified is available? It should be seen at http://your_url:4444/grid/console
You can also not specify the version in the config file as such: 
```
 {
      "browserName": "chrome",
      "platform": "windows"
 }
```

**Comment by ethembelka** [comment]
``[](url)Hello,
I have similar error.
`off
java -Dkite.firefox.profile=/home/ethem/Documents/GitHub/KITE/third_party/firefox-h264-profiles/ -cp /home/ethem/Documents/GitHub/KITE/KITE-Engine/target/kite-jar-with-dependencies.jar:target/* org.webrtc.kite.Engine configs/search.local.config.json
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2022-12-14 00:27:51,028 INFO  - Reading '/home/ethem/Documents/GitHub/KITE/KITE-Example-Test/configs/search.local.config.json' ...
 2022-12-14 00:27:51,052 INFO  - new RoomManager(1 max per room) for null
 2022-12-14 00:27:51,052 INFO  - Please make sure that you have enough room for all users.
 2022-12-14 00:27:51,053 INFO  - getRoomUrl(random) function, with random value = true/false, will give you the base url with or without a randomized ID.
 2022-12-14 00:27:51,053 INFO  - Finished reading the configuration file
 2022-12-14 00:27:51,053 INFO  - Creating report folder if not exist at :/home/ethem/Documents/GitHub/KITE/KITE-Example-Test/kite-allure-reports/
 2022-12-14 00:27:51,055 INFO  - Running {"type":"interop","name":"KiteExampleSearchTest %ts","testImpl":"org.webrtc.kite.example.KiteExampleSearchTest","description":"This example test opens google and searches for Cosmo Software Consulting and verify the first result","tupleSize":1,"noOfThreads":1,"maxRetryCount":0,"delayForClosing":0,"permute":true} ...
 2022-12-14 00:27:51,057 INFO  - Executing {"type":"interop","name":"KiteExampleSearchTest %ts","testImpl":"org.webrtc.kite.example.KiteExampleSearchTest","description":"This example test opens google and searches for Cosmo Software Consulting and verify the first result","tupleSize":1,"noOfThreads":1,"maxRetryCount":0,"delayForClosing":0,"permute":true} for 1 browser tuples with size :1
 2022-12-14 00:27:51,059 INFO  - current phase in test manager has been set to DEFAULT
 2022-12-14 00:27:51,061 INFO  - 
           |--------------------------------------------------
           | Number of registered tests: 0
           | Elapsed time: 0m0s (avg:0m0s)
           | Running test case with ID: 0/1
           | ETA (for KiteExampleSearchTest %ts): Estimating..
           |--------------------------------------------------
 2022-12-14 00:27:51,062 INFO  - execute(DEFAULT) for the test case: LIN_ch_108 (2022-12-14-002751)
 2022-12-14 00:27:51,062 INFO  - Not load test, init report for test
 2022-12-14 00:27:51,063 INFO  - Finished filling out initial report for phase 
 2022-12-14 00:27:51,063 INFO  - payload handling
 2022-12-14 00:27:51,063 INFO  - the payload is {"test1":"ONE","test2":"TWO"}
 2022-12-14 00:27:51,064 INFO  - Creating runners
 2022-12-14 00:27:51,064 INFO  - Start creating the TestRunner id 0 in 0ms
 2022-12-14 00:27:51,069 INFO  - unknown(no Web Driver): Creating web driver for {"app":false,"kind":"browser","logger":{"name":"org.webrtc.kite.config.client.Client","debugEnabled":true},"count":5,"clientIndex":0,"fullReset":false,"jsonConfig":{"headless":{},"browserName":{},"version":{},"platform":{}},"capability":{"headless":false,"windowSize":"1920,1200","technologyPreview":false,"useFakeMedia":true,"flags":[],"extraCapabilities":{},"maxInstances":5,"gateway":"none"},"paas":{"specList":[],"networkProfile":{"corrupt":0,"delay":0,"cleanUpCommand":"","bandwidth":0,"packetloss":0,"name":"NONE","id":"","duplicate":0,"command":""},"availableSlots":4,"type":"local","region":"NC","url":"http://localhost:4444/wd/hub"},"name":"0","networkProfile":{"corrupt":0,"delay":0,"cleanUpCommand":"","bandwidth":0,"packetloss":0,"name":"","id":"","duplicate":0,"command":""},"exclude":false,"browserSpecs":{"extension":"","profile":"","driverString":"-Dwebdriver.chrome.driver=./chromedriver","browserName":"chrome","version":"108","deviceName":"unknown","platform":"LINUX"},"region":"NC"}
 Dec 14, 2022 12:27:51 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2022-12-14 00:27:51,617 INFO  - unknown(no Web Driver):  [PASSED] Initiate webDriver for client
 2022-12-14 00:27:51,628 INFO  - Starting the execution of the test runners in parallel 
 2022-12-14 00:27:51,629 INFO  - Start processing the TestRunner(DEFAULT) id 0 in 0ms
 2022-12-14 00:27:52,457 INFO  - ch108_LINUX-cb453 - 0:  [PASSED] Open https://google.com and look for CoSMo Software Consulting
 2022-12-14 00:27:53,757 ERROR - Step failed:
   message = The title of the first Google result was not correct: 
Expected: CoSMo Software - Cosmo Software but found Software & Consulting for the Digital Transformation of Companies | COSMO CONSULT

 2022-12-14 00:27:53,758 WARN  - ch108_LINUX-cb453 - 0: [SKIPPING] Get the browser console logs.
 2022-12-14 00:27:53,758 INFO  - ch108_LINUX-cb453 - 0:  [FAILED] Open first result on Google result page and verify the page title
 2022-12-14 00:27:53,758 INFO  - execute(DEFAULT) completed.
 2022-12-14 00:27:53,758 INFO  - Terminating, quiting webdriver
 2022-12-14 00:27:53,758 INFO  - Closing down webDrivers
 2022-12-14 00:27:53,821 INFO  - Test FAILED
 2022-12-14 00:27:53,821 INFO  - Matrix runner at last phase, ending. 
 2022-12-14 00:27:53,825 WARN  - Adding [0] to retry list..
 2022-12-14 00:27:53,826 INFO  - Reading '/home/ethem/Documents/GitHub/KITE/KITE-Example-Test/configs/search.local.config.json' ...
 2022-12-14 00:27:53,826 WARN  - Done! Some test cases might need to be rerun!
 2022-12-14 00:27:53,827 INFO  - Reading '/home/ethem/Documents/GitHub/KITE/KITE-Example-Test/configs/search.local.config.json' ...
 2022-12-14 00:27:53,827 INFO  - shutdownExecutors() done.
`
But i have see web driver on (http://localhost:4444/grid/console)

**Comment by ethembelka** [comment]
file:///home/ethem/Pictures/Screenshot%20from%202022-12-06%2016-35-16.png

**Comment by ethembelka** [comment]
Java  Version is:
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu122.04, mixed mode, sharing)

Maven Version is:
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 17.0.5, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-56-generic", arch: "amd64", family: "unix"
