### ISSUE TITLE
 getting UnableToCreateProfileException for firefox v70

### ISSUE THREAD

**Issue by ImranTelebu** [webrtc/KITE#89]
Hi, I am getting the below Error.

 2019-11-11 10:58:05,943 ERROR - org.openqa.selenium.firefox.UnableToCreateProfileException: Given model profile directory does not exist: D:\Join_Kite\KITE\third_party\windows
Driver info: driver.version: unknown
        at org.openqa.selenium.firefox.FirefoxProfile.verifyModel(FirefoxProfile.java:169)
        at org.openqa.selenium.firefox.FirefoxProfile.<init>(FirefoxProfile.java:85)
        at org.openqa.selenium.firefox.FirefoxProfile.<init>(FirefoxProfile.java:72)
        at org.webrtc.kite.WebDriverFactory.setCommonFirefoxOptions(WebDriverFactory.java:367)
        at org.webrtc.kite.WebDriverFactory.buildBrowserCapabilities(WebDriverFactory.java:128)
        at org.webrtc.kite.WebDriverFactory.createCapabilities(WebDriverFactory.java:183)
        at org.webrtc.kite.WebDriverFactory.createWebDriver(WebDriverFactory.java:220)
        at org.webrtc.kite.config.client.Client.createWebDriver(Client.java:893)
        at org.webrtc.kite.tests.TestRunner.<init>(TestRunner.java:56)
        at org.webrtc.kite.tests.KiteBaseTest.createTestRunners(KiteBaseTest.java:90)
        at org.webrtc.kite.tests.KiteBaseTest.init(KiteBaseTest.java:168)
        at org.webrtc.kite.tests.KiteBaseTest.execute(KiteBaseTest.java:120)
        at org.webrtc.kite.TestManager.call(TestManager.java:196)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by namvuCosmo** [comment]
Hi, 

Can you please give us the exact command line you used to get this error?

**Comment by ImranTelebu** [comment]
yes sure,


 D:\TelebuJoin_Kite\KITE\Join>r configs\sample.config.json
java  -Dkite.firefox.profile="D:\TelebuJoin_Kite\KITE/third_party/" -cp "D:\TelebuJoin_Kite\KITE/KITE-Engine/target/kite-jar-with-dependencies.jar;target/*" org.webrtc.kite.Engine configs\sample.config.json
2019-11-11 11:43:47,362 INFO  - Reading 'configs\sample.config.json' ...
 2019-11-11 11:43:47,402 INFO  - new RoomManager(1) for null
 2019-11-11 11:43:47,402 INFO  - Finished reading the configuration file
 2019-11-11 11:43:47,417 INFO  - Creating report folder if not exist at :D:\TelebuJoin_Kite\KITE\Join/kite-allure-reports/
 2019-11-11 11:43:47,422 INFO  - Running {"type":"interop","name":"TelebucallerTest %ts","testImpl":"org.webrtc.kite.sample.test.JoinCrossBrowserTest","description":"searches for telebu and initiate call","tupleSize":1,"noOfThreads":1,"maxRetryCount":0,"delayForClosing":0,"permute":true} ...
 2019-11-11 11:43:47,570 INFO  - Executing {"type":"interop","name":"TelebucallerTest %ts","testImpl":"org.webrtc.kite.sample.test.JoinCrossBrowserTest","description":"searches for telebu and initiate call","tupleSize":1,"noOfThreads":1,"maxRetryCount":0,"delayForClosing":0,"permute":true} for 2 browser tuples with size :1
 2019-11-11 11:43:47,584 INFO  - Finished filling out initial report for phase
 2019-11-11 11:43:47,585 INFO  -
           |--------------------------------------------------
           | Number of registered tests: 1
           | Elapsed time: 0m0s (avg:0m0s)
           | Running test case with ID: 1/2
           | ETA (for TelebucallerTest %ts): Estimating..
           |--------------------------------------------------
 2019-11-11 11:43:47,585 INFO  - execute(DEFAULT) for the test case: WIN_ch (2019-11-11-114347)
 2019-11-11 11:43:47,594 INFO  - Creating webdriver for {"platform":"WINDOWS","count":1,"exclude":false,"paas":"local","remoteUrl":"http://localhost:4444/wd/hub","useFakeMedia":true,"windowSize":"1920,1200","flags":[],"browserName":"chrome","headless":false,"technologyPreview":false}
 Nov 11, 2019 11:43:53 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
in host
2019-11-11 11:43:59,116 INFO  - Starting the execution of the test runners sequentially
 2019-11-11 11:43:59,117 INFO  - ch78_WIN-7cd94: open join and setup room
 email clicked
Your OTP is 506568
click start
skip echo
in meetingname fill
meeting name done
sharelink
2019-11-11 11:44:15,451 INFO  - execute(DEFAULT) completed.
 2019-11-11 11:44:15,452 INFO  - closeDrivers: closing down 1 webDrivers
 2019-11-11 11:44:15,497 INFO  - Test PASSED
 2019-11-11 11:44:15,498 INFO  - Finished filling out initial report for phase
 2019-11-11 11:44:15,512 INFO  -
           |--------------------------------------------------
           | Number of registered tests: 2
           | Elapsed time: 0m27s (avg:0m27s)
           | Running test case with ID: 2/2
           | ETA (for TelebucallerTest %ts): 0m27s
           |--------------------------------------------------
 2019-11-11 11:44:15,513 INFO  - execute(DEFAULT) for the test case: WIN_fi (2019-11-11-114415)
 2019-11-11 11:44:15,513 INFO  - Creating webdriver for {"platform":"WINDOWS","count":1,"exclude":false,"paas":"local","remoteUrl":"http://localhost:4444/wd/hub","useFakeMedia":true,"windowSize":"1920,1200","flags":[],"browserName":"firefox","headless":false,"technologyPreview":false}
 2019-11-11 11:44:15,522 ERROR - org.openqa.selenium.firefox.UnableToCreateProfileException: Given model profile directory does not exist: D:\TelebuJoin_Kite\KITE\third_party\windows
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-1SD5N80', ip: '169.254.169.205', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: unknown
        at org.openqa.selenium.firefox.FirefoxProfile.verifyModel(FirefoxProfile.java:169)
        at org.openqa.selenium.firefox.FirefoxProfile.<init>(FirefoxProfile.java:85)
        at org.openqa.selenium.firefox.FirefoxProfile.<init>(FirefoxProfile.java:72)
        at org.webrtc.kite.WebDriverFactory.setCommonFirefoxOptions(WebDriverFactory.java:367)
        at org.webrtc.kite.WebDriverFactory.buildBrowserCapabilities(WebDriverFactory.java:128)
        at org.webrtc.kite.WebDriverFactory.createCapabilities(WebDriverFactory.java:183)
        at org.webrtc.kite.WebDriverFactory.createWebDriver(WebDriverFactory.java:220)
        at org.webrtc.kite.config.client.Client.createWebDriver(Client.java:893)
        at org.webrtc.kite.tests.TestRunner.<init>(TestRunner.java:56)
        at org.webrtc.kite.tests.KiteBaseTest.createTestRunners(KiteBaseTest.java:90)
        at org.webrtc.kite.tests.KiteBaseTest.init(KiteBaseTest.java:168)
        at org.webrtc.kite.tests.KiteBaseTest.execute(KiteBaseTest.java:120)
        at org.webrtc.kite.TestManager.call(TestManager.java:196)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

 2019-11-11 11:44:15,523 ERROR - Exception while populating web drivers, closing already created webdrivers...
org.webrtc.kite.exception.KiteGridException: UnableToCreateProfileException creating webdriver for
{"platform":"WINDOWS","count":1,"exclude":false,"paas":"local","remoteUrl":"http://localhost:4444/wd/hub","useFakeMedia":true,"windowSize":"1920,1200","flags":[],"browserName":"firefox","headless":false,"technologyPreview":false}:
Given model profile directory does not exist: D:\TelebuJoin_Kite\KITE\third_party\windows
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-1SD5N80', ip: '169.254.169.205', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: unknown
        at org.webrtc.kite.config.client.Client.createWebDriver(Client.java:902)
        at org.webrtc.kite.tests.TestRunner.<init>(TestRunner.java:56)
        at org.webrtc.kite.tests.KiteBaseTest.createTestRunners(KiteBaseTest.java:90)
        at org.webrtc.kite.tests.KiteBaseTest.init(KiteBaseTest.java:168)
        at org.webrtc.kite.tests.KiteBaseTest.execute(KiteBaseTest.java:120)
        at org.webrtc.kite.TestManager.call(TestManager.java:196)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.firefox.UnableToCreateProfileException: Given model profile directory does not exist: D:\TelebuJoin_Kite\KITE\third_party\windows
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-1SD5N80', ip: '169.254.169.205', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: unknown
        at org.openqa.selenium.firefox.FirefoxProfile.verifyModel(FirefoxProfile.java:169)
        at org.openqa.selenium.firefox.FirefoxProfile.<init>(FirefoxProfile.java:85)
        at org.openqa.selenium.firefox.FirefoxProfile.<init>(FirefoxProfile.java:72)
        at org.webrtc.kite.WebDriverFactory.setCommonFirefoxOptions(WebDriverFactory.java:367)
        at org.webrtc.kite.WebDriverFactory.buildBrowserCapabilities(WebDriverFactory.java:128)
        at org.webrtc.kite.WebDriverFactory.createCapabilities(WebDriverFactory.java:183)
        at org.webrtc.kite.WebDriverFactory.createWebDriver(WebDriverFactory.java:220)
        at org.webrtc.kite.config.client.Client.createWebDriver(Client.java:893)
        ... 9 more

 2019-11-11 11:44:15,525 ERROR - Step broken:
   message = Exception while populating web drivers

 2019-11-11 11:44:15,547 INFO  - execute(DEFAULT) completed.
 2019-11-11 11:44:15,548 INFO  - closeDrivers: closing down 1 webDrivers
 2019-11-11 11:44:15,549 ERROR - Exception while closing/quitting the WebDriver
 java.lang.NullPointerException
        at io.cosmosoftware.kite.util.WebDriverUtils.closeDrivers(WebDriverUtils.java:128)
        at org.webrtc.kite.tests.KiteBaseTest.terminate(KiteBaseTest.java:196)
        at org.webrtc.kite.tests.KiteBaseTest.execute(KiteBaseTest.java:136)
        at org.webrtc.kite.TestManager.call(TestManager.java:196)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
2019-11-11 11:44:15,561 INFO  - Test FAILED
 2019-11-11 11:44:15,604 WARN  - Adding [1] to retry list..
 2019-11-11 11:44:15,608 INFO  - Reading 'configs\sample.config.json' ...
 2019-11-11 11:44:15,609 WARN  - Done! Some test cases might need to be rerun!
 2019-11-11 11:44:15,609 INFO  - Reading 'configs\sample.config.json' ...
 2019-11-11 11:44:15,623 INFO  - shutdownExecutors() done.

**Comment by namvuCosmo** [comment]
I see.

This part here doesn't look right to me:

> D:\TelebuJoin_Kite\KITE\Join>r configs\sample.config.json
> java -Dkite.firefox.profile="D:\TelebuJoin_Kite\KITE/third_party/" -cp "D:\TelebuJoin_Kite\KITE/KITE-Engine/target/kite-jar-with-dependencies.jar;target/*" org.webrtc.kite.Engine configs\sample.config.json

Do you have KITE's latest code from github? Because in our script, the run command `r` is pointing to the folder `third_party/firefox-h264-profiles`  (instead of `third_party` as in your log):

![image](https://user-images.githubusercontent.com/27989546/68566162-87e5af80-0490-11ea-97b2-e4099dc3cf49.png)

So make sure you have the correct path to the firefox profiles. If you don't need it, just run:
` java -cp "D:\TelebuJoin_Kite\KITE/KITE-Engine/target/kite-jar-with-dependencies.jar;target/*" org.webrtc.kite.Engine configs\sample.config.json`

or remove the `-Dkite.firefox.profile="%KITE_HOME%/third_party/firefox-h264-profiles/" ` in the script (at `KITE/scripts/YOUR_OS/path/r`), the you can run as normal with `r`

Hope this helps

**Comment by ImranTelebu** [comment]
I just checked r command is set correctly for me

![Untitled](https://user-images.githubusercontent.com/51738071/68567339-ca05f580-047e-11ea-9bf3-1c97c7492344.png)

but when I run the code it is taking till D:\TelebuJoin_Kite\KITE/third_party/.


D:\TelebuJoin_Kite\KITE\Join>r configs\sample.config.json
java  -Dkite.firefox.profile="D:\TelebuJoin_Kite\KITE/third_party/" -cp "D:\TelebuJoin_Kite\KITE/KITE-Engine/target/kite-jar-with-dependencies.jar;target/*" org.webrtc.kite.Engine configs\sample.config.json
2019-11-11 12:23:02,336 INFO  - Reading 'configs\sample.config.json' ...
 2019-11-11 12:23:02,383 INFO  - new RoomManager(1) for null
 2019-11-11 12:23:02,383 INFO  - Finished reading the configuration file
 2019-11-11 12:23:02,399 INFO  - Creating report folder if not exist at :D:\TelebuJoin_Kite\KITE\Join/kite-allure-reports/

**Comment by namvuCosmo** [comment]
Do you have other copy of KITE folder anywhere else?

Try `where r` to make sure that you are running the right `r.bat`.

If it is the right file and the same behavior still persists, please use the command without the firefox profile for now:
`java -cp "D:\TelebuJoin_Kite\KITE/KITE-Engine/target/kite-jar-with-dependencies.jar;target/*" org.webrtc.kite.Engine configs\sample.config.json`

I'm not sure that I can reproduce this error.

**Comment by ImranTelebu** [comment]
Yes, I have a copy of kite.. and after deleting its working fine...Thank You so much for your support and time.
